version: '3.7'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'meat-n-heat'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    restart: 'no'
